TARGETS=iir4.v tb.v 
LIB=\
../../gen/combo_mul_2.v \
../../gen/combo_sum_2.v \
../../gen/combo_sum_3.v \
../../gen/delay_line2x3.v \
../../gen/delay_line3x4.v \
../../gen/gen_seq.v \
../../gen/mul_2.v \
../../gen/regin.v \
../../gen/regout.v \
../../gen/sum_4.v \

include ../rules.mk
