// ---------------------------------------------------------- 
//  File automatically generated by pp preprocessor 
//  Please ***DO NOT EDIT***. Perform changes on SOURCE FILE 
//  CMD LINE: pp.pl -q -ips dbg.pl ../../lib/pp.data_mem.v -o - 
// ---------------------------------------------------------- 


module data_mem(/*autoarg*/);

parameter DM_AW = 10;
parameter DM_DW = 32;
parameter RAM_DEPTH = 1 << DM_AW;
parameter BANK_SIZE = RAM_DEPTH >> 2;

input                                   clk;
input                                   rst_n;
input  [DM_AW-1:0]                      mem_addr;
input  [DM_DW-1:0]                      mem_wdata;
input                                   mem_wr_en;
input                                   mem_rd_en;
output [DM_DW-1:0]                      mem_rdata;
output                                  mem_rdata_vld;

reg  [DM_DW -1:0]                       mem_rdata_1;
reg                                     mem_rdata_vld_1;

  wire [DM_DW-1:0] mem_rdata_0;

  ram_bank #(DM_DW, DM_AW, BANK_SIZE) u_ram_bank_0 (
    .clk  (clk), 
    .we   (mem_wr_en), 
    .d    (mem_wdata), 
    .addr (mem_addr), 
    .q    (mem_rdata_0)
  );

  wire mem_read = mem_rd_en & ~mem_wr_en;

  reg mem_read_1;
  always @(posedge clk) begin
     mem_read_1 <= mem_read;
  end

  always @(/*AS*/) begin
     mem_rdata_1     = {DM_DW{1'b0}};
     mem_rdata_vld_1 = 1'b0;
     if (mem_read_1) begin
         mem_rdata_1     = mem_rdata_0;
         mem_rdata_vld_1 = 1'b1;
     end
  end


  assign mem_rdata     = mem_rdata_1;
  assign mem_rdata_vld = mem_rdata_vld_1;


endmodule // data_mem

// PP_FILENAME="data_mem.v"
