TARGETS=matrix_mm.v tb.v 
LIB=\
../../gen/cross_seq.v \
../../gen/gen_seq.v \
../../gen/getmi.v \
../../gen/mul_2.v \
../../gen/set_mi.v \
../../gen/sum_2.v \
../../gen/sum_reduce.v \

include ../rules.mk
