TARGETS=matrix.v tb.v 
LIB=\
../../gen/arb_3.v \
../../gen/buffer_fifo10.v \
../../gen/cross_seqx2.v \
../../gen/gen_seq.v \
../../gen/getmi.v \
../../gen/mul_2.v \
../../gen/range.v \
../../gen/setmi.v \
../../gen/sum_reduce.v \
../../gen/wait_for_all_fifo2_2.v \
../../lib/data_mem_mon.v \
../../lib/ram_bank.v \
../../lib/sync_fifo.v \

include ../rules.mk

